language: bash
script:
  - export "DISPLAY=:0"
  - sudo modprobe fuse
  - bash jetbrains-toolbox-app-installer.ubuntu.sh
  - test -x "$HOME/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox" || exit 1
