language: bash
script:
  - sudo apt-get update
  - sudo apt-get install -y xvfb
  - sudo modprobe fuse
  - xvfb-run bash jetbrains-toolbox-app-installer.ubuntu.sh
  - test -x "$HOME/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox" || exit 1
